### ISSUE TITLE
OWNER TO dba;

### ISSUE THREAD

**Issue by tmorganbrown** [mathieubossaert/central2pg#3]
Hi Mathieu,

After giving up on this for awhile, I'm back and really determined to get this to work. I just tested the central2pg.sql script from master and got the following error

ERROR:  role "dba" does not exist
SQL state: 42704

It comes from the line 574:

OWNER TO dba;

Should it be OWNER TO CURRENT_USER instead or are there dependencies on role dba in the functions?

**Comment by mathieubossaert** [comment]
Hi !

I forgot to drop dba (my user) references... 
You can adapt it to your own. No other dependencies on this role.

**Comment by tmorganbrown** [comment]
Great. I just changed it to CURRENT_USER and the script adds the functions

**Comment by mathieubossaert** [comment]
thank you I will make the correction
