### ISSUE TITLE
Successfully run... zero results

### ISSUE THREAD

**Issue by tmorganbrown** [mathieubossaert/central2pg#4]
Hey again.

After getting the functions added to my odk_central schema I run the select odk_central.odk_central_to_pg() call with the correct server details. The script executes successfully, but returns void with no tables created. Any ideas?

Cheers,
Theron

**Comment by mathieubossaert** [comment]
Do you use a Central "Web User" user with correct credentials.
I am sorry for the moment I do not try to catch curl messages. You should run the curl command from your console to get more details.

**Comment by tmorganbrown** [comment]
I'm able to curl the svc file using the same credentials while logged into the database server.

**Comment by mathieubossaert** [comment]
ok we will find what happens.

**Comment by mathieubossaert** [comment]
I will contact you by private message on the ODK Forum.

**Comment by mathieubossaert** [comment]
Was due $ character at the beginning of a parameter value
