### ISSUE TITLE
get_file_from_central row 25 references wrong relation

### ISSUE THREAD

**Issue by PhilKnight** [mathieubossaert/central2pg#7]
I think I have found an error in get_file_from_central function. In row 25 the COPY statement references central_json_from_central when the temp table created for the function is central_media_from_central. Shouldn't the function be referencing the temp table created as part of the function.

**Comment by mathieubossaert** [comment]
THanks @PhilKnight !

You're right, I didn't found it because in the end the function works fine. So I think postgres runs the curl cmd and after fails to copy the command result. But downloaded attachments are well saved on destination.
I'll commit a correction in a few minutes. Thanks a lot !
